### ISSUE TITLE
Screenshots 

### ISSUE THREAD

**Issue by rubyFeedback** [ekzhang/composing.studio#23]
Could more screenshots be added? Perhaps on windows or linux? And different functionality?

Thsi is mostly to get people interested. I only recently read it on reddit so ...

**Comment by ekzhang** [comment]
Hey @rubyFeedback, thanks for the suggestion! We're really excited about sharing the app with others, and we'd love to include more screenshots in the future. Is there any specific feature you had in mind?

If you wanted to share your own screenshot, that would be great as well!
