### ISSUE TITLE
empty page

### ISSUE THREAD

**Issue by E-Ruellan** [ekzhang/composing.studio#26]
Thanks for your work on Composing Studio. I would like to report a bug.

Sometime the entire page becomes blank and I can't recover my score.
I suspect it happens when I enter incoherent ABC notation.

Examples:
https://composing.studio/closed-vacation-2567
https://composing.studio/smooth-writer-8672

**Comment by ekzhang** [comment]
Thanks for the bug report. It looks like the link you presented has this input, and I have been able to reproduce the failure:

```
T:Taigiin Uria, voix harmonique 2
M:3/4
C:trad. ou Hosoo & Transmongolia ?
Z:JdL (notation ABC : ER)
Q:1/4=140
L:1/4
K:EMaj
V:1 name="harmoniques, voix 2" clef="
z3|z3|z3|z3|
EE2|FG2|FB2|GG2|EE2|FG2|Bc2|B3|
ze2-|e3|cB2|cB2|GG2|BF2|FGF|E3|
V:2 name="bourdon" clef="bass"
[E,B,][E,2B,2]|[E,E]|[E,2E2]|[E,B,][E,2B,2]|[E,E]|[E,2E2]|
% E,3|z3-|z3|z3|E,3|z3-|z3|z3|
% zE,2|z3-|z3|z3|E,3|z3-|z3|z3|
V:3 name="rythme" clef="perc"
CCz|CCz|CCz|CCz|
CCz|CCz|CCz|CCz|CCz|CCz|CCz|CCz|
CCz|CCz|CCz|CCz|CCz|CCz|CCz|CCz|
```

**Comment by ekzhang** [comment]
Thanks Emmanuel for the detailed bug report and explanation! The page definitely shouldn't turn white in any case; we'll figure out how to fix that.
